services:
  crdb-single:
    image: cockroachdb/cockroach:v24.3.0
    container_name: crdb-single
    hostname: crdb-single
    command:
      - start-single-node
      - --insecure
      - --cache=.25
      - --max-sql-memory=.25
    ports:
      - "26260:26257"
      - "8083:8080"
    volumes:
      - crdb-single-data:/cockroach/cockroach-data
    mem_limit: 512m
    healthcheck:
      test:
        - CMD-SHELL
        - cockroach node status --insecure --host=localhost:26257 || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  crdb-single-data: