-- Base de datos del PFC AGLS - TiendaTech
CREATE DATABASE IF NOT EXISTS tiendatech;

USE tiendatech;

-- Clientes registrados en la plataforma
CREATE TABLE IF NOT EXISTS clientes (
    cliente_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    provincia VARCHAR(60) NOT NULL,
    fecha_registro TIMESTAMP NOT NULL DEFAULT current_timestamp()
);

-- Productos de hardware
CREATE TABLE IF NOT EXISTS productos (
    producto_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    categoria VARCHAR(60) NOT NULL,
    precio DECIMAL(10,2) NOT NULL CHECK (precio >= 0),
    stock INT NOT NULL CHECK (stock >= 0)
);

-- Tabla principal para la fragmentación horizontal
CREATE TABLE IF NOT EXISTS pedidos (
    pedido_id INT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id INT NOT NULL,
    fecha_pedido TIMESTAMP NOT NULL DEFAULT current_timestamp(),
    provincia_entrega VARCHAR(60) NOT NULL,
    estado VARCHAR(30) NOT NULL
        CHECK (
            estado IN (
                'PENDIENTE',
                'PAGADO',
                'ENVIADO',
                'ENTREGADO',
                'CANCELADO'
            )
        ),
    total DECIMAL(12,2) NOT NULL CHECK (total >= 0),

    CONSTRAINT pk_pedidos
        PRIMARY KEY (provincia_entrega, pedido_id),

    CONSTRAINT uq_pedidos_id
        UNIQUE (pedido_id),

    CONSTRAINT fk_pedido_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(cliente_id)
);

-- Productos incluidos en cada pedido
CREATE TABLE IF NOT EXISTS detalle_pedido (
    detalle_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id INT NOT NULL,
    producto_id INT NOT NULL,
    cantidad INT NOT NULL CHECK (cantidad > 0),
    precio_unitario DECIMAL(10,2) NOT NULL CHECK (precio_unitario >= 0),
    subtotal DECIMAL(12,2) NOT NULL CHECK (subtotal >= 0),

    CONSTRAINT fk_detalle_pedido
        FOREIGN KEY (pedido_id)
        REFERENCES pedidos(pedido_id),

    CONSTRAINT fk_detalle_producto
        FOREIGN KEY (producto_id)
        REFERENCES productos(producto_id)
);